export const FETCH_RESUME_INIT = 'FETCH_RESUME_INIT'
export const FETCH_RESUME = 'FETCH_RESUME'
export const FETCH_RESUME_COMPLETED = 'FETCH_RESUME_COMPLETED'
export const FETCH_RESUME_FAILED = 'FETCH_RESUME_FAILED'
