export const ADJUST_CONTENT_VIEW_HEIGHT = 'ADJUST_CONTENT_VIEW_HEIGHT'
export const REMOVE_TAG = 'REMOVE_TAG'
export const ADJUST_TAG_INPUT_INDENT = 'ADJUST_TAG_INPUT_INDENT'
export const ADD_TAG = 'ADD_TAG'

export const UPDATE_ARTICLE_FIELD = 'UPDATE_ARTICLE_FIELD'

export const CHECK_ARTICLE_FIELDS = 'CHECK_ARTICLE_FIELDS'

export const REQUEST_SAVE_ARTICLE_INIT = 'REQUEST_SAVE_ARTICLE_INIT'
export const REQUEST_SAVE_ARTICLE = 'REQUEST_SAVE_ARTICLE'
export const REQUEST_SAVE_ARTICLE_COMPLETED = 'REQUEST_SAVE_ARTICLE_COMPLETED'
export const REQUEST_SAVE_ARTICLE_FAILED = 'REQUEST_SAVE_ARTICLE_FAILED'
