export const ADJUST_CONTENT_VIEW_HEIGHT = 'ADJUST_CONTENT_VIEW_HEIGHT'
export const REMOVE_TAG = 'REMOVE_TAG'
export const ADJUST_TAG_INPUT_INDENT = 'ADJUST_TAG_INPUT_INDENT'
export const ADD_TAG = 'ADD_TAG'

export const UPDATE_TITLE_FIELD = 'UPDATE_TITLE_FIELD'
export const UPDATE_SUMMARY_FIELD = 'UPDATE_SUMMARY_FIELD'
export const UPDATE_CONTENT_FIELD = 'UPDATE_CONTENT_FIELD'
export const UPDATE_CREATED_DATE_FIELD = 'UPDATE_CREATED_DATE_FIELD'

export const CHECK_ARTICLE_FIELDS = 'CHECK_ARTICLE_FIELDS'

export const REQUEST_SAVE_ARTICLE_INIT = 'REQUEST_SAVE_ARTICLE_INIT'
export const REQUEST_SAVE_ARTICLE = 'REQUEST_SAVE_ARTICLE'
export const REQUEST_SAVE_ARTICLE_COMPLETED = 'REQUEST_SAVE_ARTICLE_COMPLETED'
export const REQUEST_SAVE_ARTICLE_FAILED = 'REQUEST_SAVE_ARTICLE_FAILED'
