export const ADJUST_CONTENT_VIEW_HEIGHT = 'ADJUST_CONTENT_VIEW_HEIGHT'
export const REMOVE_TAG = 'REMOVE_TAG'
export const ADJUST_TAG_INPUT_INDENT = 'ADJUST_TAG_INPUT_INDENT'
export const ADD_TAG = 'ADD_TAG'

export const UPDATE_ARTICLE_FIELD = 'UPDATE_ARTICLE_FIELD'

export const CHECK_ARTICLE_FIELDS = 'CHECK_ARTICLE_FIELDS'

export const REQUEST_SAVE_ARTICLE_INIT = 'REQUEST_SAVE_ARTICLE_INIT'
export const REQUEST_SAVE_ARTICLE = 'REQUEST_SAVE_ARTICLE'
export const REQUEST_SAVE_ARTICLE_COMPLETED = 'REQUEST_SAVE_ARTICLE_COMPLETED'
export const REQUEST_SAVE_ARTICLE_FAILED = 'REQUEST_SAVE_ARTICLE_FAILED'

export const GET_ARTICLE_TO_EDIT = 'GET_ARTICLE_TO_EDIT'
export const GET_ARTICLE_TO_EDIT_COMPLETED = 'GET_ARTICLE_TO_EDIT_COMPLETED'
export const GET_ARTICLE_TO_EDIT_FAILED = 'GET_ARTICLE_TO_EDIT_FAILED'

export const REQUEST_DELETE_ARTICLE_INIT = 'REQUEST_DELETE_ARTICLE_INIT'
export const REQUEST_DELETE_ARTICLE = 'REQUEST_DELETE_ARTICLE'
export const REQUEST_DELETE_ARTICLE_COMPLETED = 'REQUEST_DELETE_ARTICLE_COMPLETED'
export const REQUEST_DELETE_ARTICLE_FAILED = 'REQUEST_DELETE_ARTICLE_FAILED'
