export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL'
export const GET_ARTICLE_DETAIL_COMPLETED = 'GET_ARTICLE_DETAIL_COMPLETED'
export const GET_ARTICLE_DETAIL_FAILED = 'GET_ARTICLE_DETAIL_FAILED'

export const UPDATE_COMMENT_FIELD = 'UPDATE_COMMENT_FIELD'
export const CHECK_COMMENT_FIELDS = 'CHECK_COMMENT_FIELDS'

export const REQUEST_COMMENT = 'REQUEST_COMMENT'
export const REQUEST_COMMENT_COMPLETED = 'REQUEST_COMMENT_COMPLETED'
export const REQUEST_COMMENT_FAILED = 'REQUEST_COMMENT_FAILED'
