export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL'
export const GET_ARTICLE_DETAIL_COMPLETED = 'GET_ARTICLE_DETAIL_COMPLETED'
export const GET_ARTICLE_DETAIL_FAILED = 'GET_ARTICLE_DETAIL_FAILED'

export const UPDATE_COMMENT_FIELD = 'UPDATE_COMMENT_FIELD'
export const CHECK_COMMENT_FIELDS = 'CHECK_COMMENT_FIELDS'

export const REQUEST_COMMENT_INIT = 'REQUEST_COMMENT_INIT'
export const REQUEST_COMMENT = 'REQUEST_COMMENT'
export const REQUEST_COMMENT_COMPLETED = 'REQUEST_COMMENT_COMPLETED'
export const REQUEST_COMMENT_FAILED = 'REQUEST_COMMENT_FAILED'

export const REQUEST_LIKE_INIT = 'REQUEST_LIKE_INIT'
export const REQUEST_LIKE = 'REQUEST_LIKE'
export const REQUEST_LIKE_COMPLETED = 'REQUEST_LIKE_COMPLETED'
export const REQUEST_LIKE_FAILED = 'REQUEST_LIKE_FAILED'

export const REQUEST_DELETE_COMMENT_INIT = 'REQUEST_DELETE_COMMENT_INIT'
export const REQUEST_DELETE_COMMENT = 'REQUEST_DELETE_COMMENT'
export const REQUEST_DELETE_COMMENT_COMPLETED = 'REQUEST_DELETE_COMMENT_COMPLETED'
export const REQUEST_DELETE_COMMENT_FAILED = 'REQUEST_DELETE_COMMENT_FAILED'
