export const CHECK_IF_LOGGEDIN = 'CHECK_IF_LOGGEDIN'
export const CHECK_IF_LOGGEDIN_COMPLETED = 'CHECK_IF_LOGGEDIN_COMPLETED'
export const CHECK_IF_LOGGEDIN_FAILED = 'CHECK_IF_LOGGEDIN_FAILED'

export const REQUEST_LOGOUT_INIT = 'REQUEST_LOGOUT_INIT'
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT'
export const REQUEST_LOGOUT_COMPLETED = 'REQUEST_LOGOUT_COMPLETED'
export const REQUEST_LOGOUT_FAILED = 'REQUEST_LOGOUT_FAILED'

export const TOGGLE_LOGOUT_DIALOG = 'TOGGLE_LOGOUT_DIALOG'
