export const REQUEST_LOGOUT_INIT = 'REQUEST_LOGOUT_INIT'
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT'
export const REQUEST_LOGOUT_COMPLETED = 'REQUEST_LOGOUT_COMPLETED'
export const REQUEST_LOGOUT_FAILED = 'REQUEST_LOGOUT_FAILED'

export const TOGGLE_LOGOUT_DIALOG = 'TOGGLE_LOGOUT_DIALOG'
