export const UPLOAD_PICTURE_INIT = 'UPLOAD_PICTURE_INIT'
export const UPLOAD_PICTURE = 'UPLOAD_PICTURE'
export const UPLOAD_PICTURE_COMPLETED = 'UPLOAD_PICTURE_COMPLETED'
export const UPLOAD_PICTURE_FAILED = 'UPLOAD_PICTURE_FAILED'
