export const UPDATE_LOGIN_FIELD = 'UPDATE_LOGIN_FIELD'
export const TOGGLE_PASSWORD_VISIBILITY = 'TOGGLE_PASSWORD_VISIBILITY'

export const CHECK_LOGIN_FIELDS = 'CHECK_LOGIN_FIELDS'

export const REQUEST_LOGIN_INIT = 'REQUEST_LOGIN_INIT'
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const REQUEST_LOGIN_COMPLETED = 'REQUEST_LOGIN_COMPLETED'
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED'
