export const TOGGLE_AUTH_TAB = 'TOGGLE_AUTH_TAB'

export const UPDATE_REGISTER_FIELD = 'UPDATE_REGISTER_FIELD'
export const CHECK_REGISTER_FIELDS = 'CHECK_REGISTER_FIELDS'
export const REQUEST_REGISTER_START = 'REQUEST_REGISTER_START'
export const REQUEST_REGISTER_FAIL = 'REQUEST_REGISTER_FAIL'
export const REQUEST_REGISTER_DONE = 'REQUEST_REGISTER_DONE'
export const REQUEST_REGISTER_RESET = 'REQUEST_REGISTER_RESET'

export const UPDATE_LOGIN_FIELD = 'UPDATE_LOGIN_FIELD'
export const CHECK_LOGIN_FIELDS = 'CHECK_LOGIN_FIELDS'
export const TOGGLE_LOGIN_PASSWORD_VISIBILITY = 'TOGGLE_LOGIN_PASSWORD_VISIBILITY'
