export const SWITCH_AUTH_TAB = 'SWITCH_AUTH_TAB'

export const UPDATE_REGISTER_FIELD = 'UPDATE_REGISTER_FIELD'
export const CHECK_REGISTER_FIELDS = 'CHECK_REGISTER_FIELDS'

export const REQUEST_REGISTER = 'REQUEST_REGISTER'
export const REQUEST_REGISTER_START = 'REQUEST_REGISTER_START'
export const REQUEST_REGISTER_FAIL = 'REQUEST_REGISTER_FAIL'
export const REQUEST_REGISTER_DONE = 'REQUEST_REGISTER_DONE'
